//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewOrder.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int oidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class2", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pidField;
        
        private int qtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                if ((object.ReferenceEquals(this.pidField, value) != true)) {
                    this.pidField = value;
                    this.RaisePropertyChanged("pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pname {
            get {
                return this.pnameField;
            }
            set {
                if ((object.ReferenceEquals(this.pnameField, value) != true)) {
                    this.pnameField = value;
                    this.RaisePropertyChanged("pname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class3", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string osField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string otypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oxmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string os {
            get {
                return this.osField;
            }
            set {
                if ((object.ReferenceEquals(this.osField, value) != true)) {
                    this.osField = value;
                    this.RaisePropertyChanged("os");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string otype {
            get {
                return this.otypeField;
            }
            set {
                if ((object.ReferenceEquals(this.otypeField, value) != true)) {
                    this.otypeField = value;
                    this.RaisePropertyChanged("otype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string oxml {
            get {
                return this.oxmlField;
            }
            set {
                if ((object.ReferenceEquals(this.oxmlField, value) != true)) {
                    this.oxmlField = value;
                    this.RaisePropertyChanged("oxml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class4", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class4 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int order_idField;
        
        private int customer_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((this.customer_idField.Equals(value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class5", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class5 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int aidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int aid {
            get {
                return this.aidField;
            }
            set {
                if ((this.aidField.Equals(value) != true)) {
                    this.aidField = value;
                    this.RaisePropertyChanged("aid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_order", ReplyAction="*")]
        NewOrder.ServiceReference2.insert_orderResponse insert_order(NewOrder.ServiceReference2.insert_orderRequest request);
        
        // CODEGEN: Generating message contract since element name GetorderidResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getorderid", ReplyAction="*")]
        NewOrder.ServiceReference2.GetorderidResponse Getorderid(NewOrder.ServiceReference2.GetorderidRequest request);
        
        // CODEGEN: Generating message contract since element name getproductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getproducts", ReplyAction="*")]
        NewOrder.ServiceReference2.getproductsResponse getproducts(NewOrder.ServiceReference2.getproductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetstatusResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getstatus", ReplyAction="*")]
        NewOrder.ServiceReference2.GetstatusResponse Getstatus(NewOrder.ServiceReference2.GetstatusRequest request);
        
        // CODEGEN: Generating message contract since element name GetidsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getids", ReplyAction="*")]
        NewOrder.ServiceReference2.GetidsResponse Getids(NewOrder.ServiceReference2.GetidsRequest request);
        
        // CODEGEN: Generating message contract since element name Getaddress_idResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getaddress_id", ReplyAction="*")]
        NewOrder.ServiceReference2.Getaddress_idResponse Getaddress_id(NewOrder.ServiceReference2.Getaddress_idRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_orderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_order", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.insert_orderRequestBody Body;
        
        public insert_orderRequest() {
        }
        
        public insert_orderRequest(NewOrder.ServiceReference2.insert_orderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_orderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string due;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string neg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int id;
        
        public insert_orderRequestBody() {
        }
        
        public insert_orderRequestBody(string status, string due, string neg, string xml, string type, int id) {
            this.status = status;
            this.due = due;
            this.neg = neg;
            this.xml = xml;
            this.type = type;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_orderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_orderResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.insert_orderResponseBody Body;
        
        public insert_orderResponse() {
        }
        
        public insert_orderResponse(NewOrder.ServiceReference2.insert_orderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_orderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insert_orderResult;
        
        public insert_orderResponseBody() {
        }
        
        public insert_orderResponseBody(int insert_orderResult) {
            this.insert_orderResult = insert_orderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetorderidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getorderid", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.GetorderidRequestBody Body;
        
        public GetorderidRequest() {
        }
        
        public GetorderidRequest(NewOrder.ServiceReference2.GetorderidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetorderidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customer_id;
        
        public GetorderidRequestBody() {
        }
        
        public GetorderidRequestBody(int customer_id) {
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetorderidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetorderidResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.GetorderidResponseBody Body;
        
        public GetorderidResponse() {
        }
        
        public GetorderidResponse(NewOrder.ServiceReference2.GetorderidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetorderidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewOrder.ServiceReference2.Class1[] GetorderidResult;
        
        public GetorderidResponseBody() {
        }
        
        public GetorderidResponseBody(NewOrder.ServiceReference2.Class1[] GetorderidResult) {
            this.GetorderidResult = GetorderidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getproductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getproducts", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.getproductsRequestBody Body;
        
        public getproductsRequest() {
        }
        
        public getproductsRequest(NewOrder.ServiceReference2.getproductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getproductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int oid;
        
        public getproductsRequestBody() {
        }
        
        public getproductsRequestBody(int oid) {
            this.oid = oid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getproductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getproductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.getproductsResponseBody Body;
        
        public getproductsResponse() {
        }
        
        public getproductsResponse(NewOrder.ServiceReference2.getproductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getproductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewOrder.ServiceReference2.Class2[] getproductsResult;
        
        public getproductsResponseBody() {
        }
        
        public getproductsResponseBody(NewOrder.ServiceReference2.Class2[] getproductsResult) {
            this.getproductsResult = getproductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetstatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getstatus", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.GetstatusRequestBody Body;
        
        public GetstatusRequest() {
        }
        
        public GetstatusRequest(NewOrder.ServiceReference2.GetstatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetstatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cid;
        
        public GetstatusRequestBody() {
        }
        
        public GetstatusRequestBody(int cid) {
            this.cid = cid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetstatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetstatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.GetstatusResponseBody Body;
        
        public GetstatusResponse() {
        }
        
        public GetstatusResponse(NewOrder.ServiceReference2.GetstatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetstatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewOrder.ServiceReference2.Class3[] GetstatusResult;
        
        public GetstatusResponseBody() {
        }
        
        public GetstatusResponseBody(NewOrder.ServiceReference2.Class3[] GetstatusResult) {
            this.GetstatusResult = GetstatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetidsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getids", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.GetidsRequestBody Body;
        
        public GetidsRequest() {
        }
        
        public GetidsRequest(NewOrder.ServiceReference2.GetidsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetidsRequestBody {
        
        public GetidsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetidsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetidsResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.GetidsResponseBody Body;
        
        public GetidsResponse() {
        }
        
        public GetidsResponse(NewOrder.ServiceReference2.GetidsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetidsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewOrder.ServiceReference2.Class4[] GetidsResult;
        
        public GetidsResponseBody() {
        }
        
        public GetidsResponseBody(NewOrder.ServiceReference2.Class4[] GetidsResult) {
            this.GetidsResult = GetidsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Getaddress_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getaddress_id", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.Getaddress_idRequestBody Body;
        
        public Getaddress_idRequest() {
        }
        
        public Getaddress_idRequest(NewOrder.ServiceReference2.Getaddress_idRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Getaddress_idRequestBody {
        
        public Getaddress_idRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Getaddress_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getaddress_idResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewOrder.ServiceReference2.Getaddress_idResponseBody Body;
        
        public Getaddress_idResponse() {
        }
        
        public Getaddress_idResponse(NewOrder.ServiceReference2.Getaddress_idResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Getaddress_idResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NewOrder.ServiceReference2.Class5[] Getaddress_idResult;
        
        public Getaddress_idResponseBody() {
        }
        
        public Getaddress_idResponseBody(NewOrder.ServiceReference2.Class5[] Getaddress_idResult) {
            this.Getaddress_idResult = Getaddress_idResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : NewOrder.ServiceReference2.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<NewOrder.ServiceReference2.Service1Soap>, NewOrder.ServiceReference2.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewOrder.ServiceReference2.insert_orderResponse NewOrder.ServiceReference2.Service1Soap.insert_order(NewOrder.ServiceReference2.insert_orderRequest request) {
            return base.Channel.insert_order(request);
        }
        
        public int insert_order(string status, string due, string neg, string xml, string type, int id) {
            NewOrder.ServiceReference2.insert_orderRequest inValue = new NewOrder.ServiceReference2.insert_orderRequest();
            inValue.Body = new NewOrder.ServiceReference2.insert_orderRequestBody();
            inValue.Body.status = status;
            inValue.Body.due = due;
            inValue.Body.neg = neg;
            inValue.Body.xml = xml;
            inValue.Body.type = type;
            inValue.Body.id = id;
            NewOrder.ServiceReference2.insert_orderResponse retVal = ((NewOrder.ServiceReference2.Service1Soap)(this)).insert_order(inValue);
            return retVal.Body.insert_orderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewOrder.ServiceReference2.GetorderidResponse NewOrder.ServiceReference2.Service1Soap.Getorderid(NewOrder.ServiceReference2.GetorderidRequest request) {
            return base.Channel.Getorderid(request);
        }
        
        public NewOrder.ServiceReference2.Class1[] Getorderid(int customer_id) {
            NewOrder.ServiceReference2.GetorderidRequest inValue = new NewOrder.ServiceReference2.GetorderidRequest();
            inValue.Body = new NewOrder.ServiceReference2.GetorderidRequestBody();
            inValue.Body.customer_id = customer_id;
            NewOrder.ServiceReference2.GetorderidResponse retVal = ((NewOrder.ServiceReference2.Service1Soap)(this)).Getorderid(inValue);
            return retVal.Body.GetorderidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewOrder.ServiceReference2.getproductsResponse NewOrder.ServiceReference2.Service1Soap.getproducts(NewOrder.ServiceReference2.getproductsRequest request) {
            return base.Channel.getproducts(request);
        }
        
        public NewOrder.ServiceReference2.Class2[] getproducts(int oid) {
            NewOrder.ServiceReference2.getproductsRequest inValue = new NewOrder.ServiceReference2.getproductsRequest();
            inValue.Body = new NewOrder.ServiceReference2.getproductsRequestBody();
            inValue.Body.oid = oid;
            NewOrder.ServiceReference2.getproductsResponse retVal = ((NewOrder.ServiceReference2.Service1Soap)(this)).getproducts(inValue);
            return retVal.Body.getproductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewOrder.ServiceReference2.GetstatusResponse NewOrder.ServiceReference2.Service1Soap.Getstatus(NewOrder.ServiceReference2.GetstatusRequest request) {
            return base.Channel.Getstatus(request);
        }
        
        public NewOrder.ServiceReference2.Class3[] Getstatus(int cid) {
            NewOrder.ServiceReference2.GetstatusRequest inValue = new NewOrder.ServiceReference2.GetstatusRequest();
            inValue.Body = new NewOrder.ServiceReference2.GetstatusRequestBody();
            inValue.Body.cid = cid;
            NewOrder.ServiceReference2.GetstatusResponse retVal = ((NewOrder.ServiceReference2.Service1Soap)(this)).Getstatus(inValue);
            return retVal.Body.GetstatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewOrder.ServiceReference2.GetidsResponse NewOrder.ServiceReference2.Service1Soap.Getids(NewOrder.ServiceReference2.GetidsRequest request) {
            return base.Channel.Getids(request);
        }
        
        public NewOrder.ServiceReference2.Class4[] Getids() {
            NewOrder.ServiceReference2.GetidsRequest inValue = new NewOrder.ServiceReference2.GetidsRequest();
            inValue.Body = new NewOrder.ServiceReference2.GetidsRequestBody();
            NewOrder.ServiceReference2.GetidsResponse retVal = ((NewOrder.ServiceReference2.Service1Soap)(this)).Getids(inValue);
            return retVal.Body.GetidsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewOrder.ServiceReference2.Getaddress_idResponse NewOrder.ServiceReference2.Service1Soap.Getaddress_id(NewOrder.ServiceReference2.Getaddress_idRequest request) {
            return base.Channel.Getaddress_id(request);
        }
        
        public NewOrder.ServiceReference2.Class5[] Getaddress_id() {
            NewOrder.ServiceReference2.Getaddress_idRequest inValue = new NewOrder.ServiceReference2.Getaddress_idRequest();
            inValue.Body = new NewOrder.ServiceReference2.Getaddress_idRequestBody();
            NewOrder.ServiceReference2.Getaddress_idResponse retVal = ((NewOrder.ServiceReference2.Service1Soap)(this)).Getaddress_id(inValue);
            return retVal.Body.Getaddress_idResult;
        }
    }
}
